name: flutter_performance_optimizer
description: A powerful developer tool to detect performance issues (rebuilds, memory leaks, jank) with real-time AI-powered optimization suggestions.
version: 1.0.1
homepage: https://github.com/Naimish-Kumar/flutter_performance_optimizer/
repository: https://github.com/Naimish-Kumar/flutter_performance_optimizer/
issue_tracker: https://github.com/Naimish-Kumar/flutter_performance_optimizer/issues/
topics:
  - performance
  - debugging
  - developer-tools
  - optimization
  - monitoring

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_lints: ^5.0.0
  devtools_extensions: ^0.1.0

flutter:
  uses-material-design: true
